version: '3.9'

services:
  online-store:
    build: ./
    command: ./wait-for-postgres.sh db ./online-store
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DB_PASSWORD=12345

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345
    ports:
      - '5436:5432'