version: '3.9'

services:
  online-store:
    build: ./
    command: ./wait-for-postgres.sh db ./online-store
    ports:
      - '8080:8000'
    depends_on:
      - storedb
    container_name: backendapp
    environment:
      - DB_PASSWORD=12345
    networks:
      - online_store_app_network

  storedb:
    restart: unless-stopped
    image: postgres:latest
    container_name: storedb
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "storedb"
      POSTGRES_USER: "backend"
      POSTGRES_PASSWORD: "backend12345"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - '5432:5432'
    networks:
      - online_store_app_network
  
  admindb:
    image: dpage/pgadmin4:latest
    container_name: dbadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - '5050:80'
    depends_on:
      - storedb
    networks:
      - online_store_app_network
  
networks:
  online_store_app_network:
    driver: bridge